name: Build quay / nmaupu vault-secret

on:
  push:
    branches: [ main ]
    paths:
      - quay/nmaupu/vault-secret/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set environment vars
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: quay/nmaupu/vault-secret/env

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAYIO_USERNAME }}
        password: ${{ secrets.QUAYIO_TOKEN }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.tags }}
        context: ./quay/nmaupu/vault-secret/

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
