name: Build nmaupu vault-secret

on:
  push:
    branches: [ main ]
    paths:
      - docker/nmaupu/vault-secret/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo docker build . --file Dockerfile --tag my-image-name:$(date +%s)
