    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.tags }}
        context: ./${CONTEXT_PATH}/

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
