name: Build ${IMAGE_NAME}

on:
  push:
    branches: [ main ]
    paths:
      - ${CONTEXT_PATH}/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set environment vars
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: ${CONTEXT_PATH}/env

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

